In [1]:
import numpy as np
from pprint import pprint

In [2]:
V = np.ndarray((5,5))

## Floats from memory

In [3]:
pprint(V.sum(axis=0))
pprint(V.sum(axis=1))

array([3.45595404e-309, 2.76476314e-309, 3.45595443e-309, 3.45595747e-309,
       2.76476497e-309])
array([2.76476597e-309, 3.45595748e-309, 3.45595720e-309, 3.45595353e-309,
       2.76475987e-309])


In [4]:
V.sum()

1.5897394052208707e-308

This is a new cell

In [11]:
np.random.rand(25).reshape((5,5))

array([[0.12168292, 0.57512668, 0.44386763, 0.40288986, 0.36510581],
       [0.4051557 , 0.95288072, 0.72213423, 0.89455335, 0.09048518],
       [0.61536646, 0.66091168, 0.45958072, 0.03243858, 0.61118264],
       [0.53757599, 0.83171995, 0.12781048, 0.64682348, 0.10668465],
       [0.76798195, 0.81538765, 0.79743008, 0.6671788 , 0.07019022]])